### ISSUE TITLE
Comparison documentation

### ISSUE THREAD

**Issue by uittorio** [hmil/omnimock#17]
Hi, I saw that you've mentioned ts-auto-mock in the list of mocking framework.

ts-auto-mock is not a fully mocking framework. that gives matchers and verification, its simply a utility to generate mocks from typescript types.

List:

Requires Proxy: NO
Backed mocks: in ts-auto-mock mocks exists at runtime
Virtual mocks: its not a virtual mock
Function mocks: ts-auto-mock can mock functions
Undefined behavior: it doesnt apply to ts-auto-mock because we mock the entire type
Return value: YES, it does mock the return value
Mocking an exception: it doesnt apply ts auto mock because we dont provide a framework to test 
Mocking a getters or members: it does mock properties (maybe we dont support yet getters)
Call forwarding: I believe it doesnt apply to ts auto mock because is not a framework
Call fake: in ts-auto-mock you can customise what to do for a method but its global
Deep mocking: it does do it because it mock recursively the entire type
Unexpected call verification: same as above, it's not a framework
Missing call verification: same as above, it's not a framework
Matchers: same as above, it's not a framework
Verifying setters: same as above, it's not a framework
Return value type checking: same as above, it's not a framework
Arguments type checking: same as above, it's not a framework
Templated functions:  same as above, it's not a framework, but we will support soon conditional type

PS: I'm one of the creator of ts-auto-mock. Please feel free to ask any questions :)

**Comment by hmil** [comment]
Hi @uittorio, thank you for these precisions.

As far as I understand, ts-auto-mock automatically creates what is called here "backed mocks" without the need for proxy (thanks to TS transformers). Pretty neat.
The fact that it is able to generate mock function which return the correct type is a huge plus imo (as opposed to jasmine's default behavior to return "undefined" and hope for the best 😒).

There doesn't seem to be an easy way to customize the behavior of mocks on a per-test basis in ts-auto-mock, which makes the comparison difficult. For instance, how would you handle the following situation with ts-auto-mock?

```ts

class MyService {
    constructor(private dependency) {}

   getMood() {
      return dependency.fetchMood()
   }
}

setup() {
    mockDependency = createMock()
    fixture = createService(mockDependency)
}

testHappy() {
   expect(fixture.getMood()).toBe("Happy")
}

testSad() {
   // <-- somehow configure mockDependency.fetchMood to throw an error
   expect(() => fixture.getMood()).toThrow()
}
```

If this wasn't part of the design goals of ts-auto-mock then I think it is not fair to compare it in the matrix because it is not meant to do the same thing as omnimock.
Could you explain the typical application scenario for ts-auto-mock? I could add that as a note so users can better understand which module is more suited for what they are trying to do.

**Comment by uittorio** [comment]
Hi!, Ts auto mock does not have a lot of configuration utility for each different test, you can see more as a utility to simplify the creation of mocks.  Let's say you have a big interface that you want to mock but you need only one method. Instead of creating that method and casting the interface you can simply create the mock with ts-auto-mock and continue testing what you need to do. It basically gives you type safety, recursion of mocks, mocks from interface directly.

If you need to specify what a method should do you can still do it with your own framework. For example 

```ts
interface Interface {
 name: string;
 surname: string;
 getFullName(): string;
}
const mock = createMock<Interface>();
// using jasmine for example
objectMock.getFullName.and.returnValue('uittorio')

expect(objectMock.getFullName()).toBe('uittorio');

```

I believe If I was using ominimock I would use both. I would initially create a basic mock with ts-auto-mock and then give all the power that you have with omnimock. expectation, etc, etc.

Another thing I am not sure 100% of proxies (that you are using) is recursion.

How does behave the library when you mock this

```ts
interface Person {
getName(): string;
 mother: Person;
}

const mock = createMock<Person>()

```
with ts auto mock you can do this  (with a jest configuration)
```ts
mock.mother.mother.mother.getName.and.returnValue('mother name')
mock.mother.mother.mother.getName() /// mother name
````

**Comment by hmil** [comment]
OK I now have a better understanding of the scope of ts auto mock.

Your example would look like this using omnimock:

```
when(mock.mother.mother.mother.getName()).return('mother name')
mock.mother.mother.mother.getName() // mother name
mock.mother.getName() // Error: unspecified behavior
```

You can see the main difference in the last line: With omnimock, you have to explicitly specify all behaviors that you expect to be used (you can ignore those you don't expect though). Nothing is ever "filled in" for you automatically. If you forget to specify something, then the framework throws an error asking you to provide the missing behavior.

**Comment by uittorio** [comment]
Yes! And I think ominmock approach is really good! it makes sure you don't make mistake with undefined or null references in javascript!
